package org.acreo.common.exceptions;

public class VeidblockException extends Exception {

    public VeidblockException() {
    	super("Unexpected error generated by VediBlock library !");
    }

    public VeidblockException(String message) {
        super(message);
        // TODO Auto-generated constructor stub
    }

    public VeidblockException(Throwable cause) {
        super(cause);
        // TODO Auto-generated constructor stub
    }

    public VeidblockException(String message, Throwable cause) {
        super(message, cause);
        // TODO Auto-generated constructor stub
    }

}